#??? ??? ?????.
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecovery?serverTimezone=UTC
    username: root
    password: 1234

  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.type.descriptor.sql: trace